### ISSUE TITLE
Tiered Pricing Display

### ISSUE THREAD

**Issue by cmdesign** [customgento/CustomGento_ConfigurableTierPrices#3]
Hello,

I added your tiered pricing extension for configurable products in Magento 1.7.0.2-2 and it seems to be working well.  However, I seem to have a small issue with the way the tiered pricing percent savings are displayed. When I go to the front end and select the configurable product options from the drop down; the posted quantity discounts all change from the correct value to “100%”.  For example “Buy 36 for $7.00 each and save 30%” changes to “Buy 36 for $7.00 each and save 100%” as soon as I select a configurable option.  Perhaps I have not set up the product pricing or configurable pricing correctly.  Is the tiered pricing supposed to be entered in the back end on the configurable product page, all the associated simple products or both? I'm not sure if this is an issue or something I am not doing correctly on my end.  Thanks for your help!

**Comment by cmdesign** [comment]
Hi Simon,

 

Does your extension also adjust the prices for product options?

 

Thanks again

**Comment by sprankhub** [comment]
No. A paid version which supports custom options may/will follow.

**Comment by cmdesign** [comment]
Do you know if any other shopping carts offer tier pricing for configurable products?

Thanks again

**Comment by sprankhub** [comment]
No idea

**Comment by cmdesign** [comment]
So is 1.7.0.2 the only version that has the issue with “100%” showing for the discount?  Do all versions since work fine?

 

Thanks

**Comment by sprankhub** [comment]
I do not know. Try it...

**Comment by cmdesign** [comment]
Hi Simon,

 

I found this and thought you may be interested.  Is it something like what you had in mind?  I would be interested in your thoughts about it.  Do you think it would work alongside your extension? 

 

http://www.code4business.de/tier-prices-for-magento-custom-options-en/

 

Thanks

**Comment by sprankhub** [comment]
I know the extension. But this is something different. They implement tier prices for custom options, so that you get a discount if you e.g. buy a custom option 50 times. My extension will implement tier prices across custom options. Means if you buy one product with custom option X and the same product with custom option Y, you will get the tier price for two products.
Did not have a look at the extension and did not try, so no idea if they would work together.

**Comment by cmdesign** [comment]
Okay – if you think of it, please shoot me an email when/if your new extension is ready.  My challenge is to find a way to offer tiered pricing for the custom options, such as the number of colors and locations screen printed on t-shirts, on the same page as the t-shirt product page.  Your extension works well for the t-shirts quantities but I’m not sure how to offer quantity discounts for the options if the price differences are not equal between the number of colors printed and the quantity purchased.  The only work around I can think of is to make the screen printing a separate product with its own sku so that I can use your existing extension on it as well.  I’m not sure it will be as seamless as being order to order the screen printing from the same page as the t-shirts and have tiered pricing applied to each, however it may work for now.  If you know any other easy solutions or extension I am overlooking; I would be grateful for any tips.

 

Take care…
